export const types = {
    TODO_ADD_LIST: 'TODO_ADD_LIST',
    TODO_EMPLY_LIST: 'TODO_EMPLY_LIST',
    TODO_GET_LIST: 'TODO_GET_LIST',
    MONEY_GET: 'MONEY_GET',
    MONEY_ATT: 'MONEY_ATT',
    MONEY_SUM_SALDO: 'MONEY_SUM_SALDO',
    MONEY_SUM_CONTAS: 'MONEY_SUM_CONTAS',
    IS_LOADING_DISPLAY: 'IS_LOADING_DISPLAY',
    IS_LOADING_MONEY: 'IS_LOADING_MONEY',
    IS_LOADING_LIST: 'IS_LOADING_LIST',
    NAV_SELECT_TAB: 'NAV_SELECT_TAB'
}